parameters:
    app.locales: [fr, ar, en]
    app.default_locale: fr

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # Abstract Storage Layer Wiring
    App\Shared\Domain\Storage\FileStorageInterface:
        class: App\Shared\Infrastructure\Storage\FlysystemStorageAdapter

    # JWT Login Response Listener
    App\IdentityAccess\Application\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
