parameters:
    default_domain: 'http://localhost'

framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        default_uri: '%env(default:default_domain:DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
